# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.check = QtWidgets.QPushButton(self.centralwidget)
        self.check.setGeometry(QtCore.QRect(10, 60, 89, 25))
        self.check.setObjectName("check")
        self.salvar = QtWidgets.QPushButton(self.centralwidget)
        self.salvar.setGeometry(QtCore.QRect(330, 480, 89, 25))
        self.salvar.setObjectName("salvar")
        self.semcarimbo = QtWidgets.QPushButton(self.centralwidget)
        self.semcarimbo.setGeometry(QtCore.QRect(630, 70, 89, 25))
        self.semcarimbo.setObjectName("semcarimbo")
        self.devolucao = QtWidgets.QPushButton(self.centralwidget)
        self.devolucao.setGeometry(QtCore.QRect(630, 130, 89, 25))
        self.devolucao.setObjectName("devolucao")
        self.anotacao = QtWidgets.QPushButton(self.centralwidget)
        self.anotacao.setGeometry(QtCore.QRect(630, 170, 89, 25))
        self.anotacao.setObjectName("anotacao")
        self.reentrega = QtWidgets.QPushButton(self.centralwidget)
        self.reentrega.setGeometry(QtCore.QRect(630, 100, 89, 25))
        self.reentrega.setObjectName("reentrega")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.check.setText(_translate("MainWindow", "check"))
        self.salvar.setText(_translate("MainWindow", "salvar"))
        self.semcarimbo.setText(_translate("MainWindow", "sem carimbo"))
        self.devolucao.setText(_translate("MainWindow", "devolução"))
        self.anotacao.setText(_translate("MainWindow", "anotação"))
        self.reentrega.setText(_translate("MainWindow", "reentrega"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
